# Generated by Django 3.1.4 on 2020-12-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=100)),
                ('game_creator', models.CharField(max_length=50)),
                ('game_opponent', models.CharField(max_length=50)),
                ('is_over', models.BooleanField(default=False)),
            ],
        ),
    ]
