# Generated by Django 3.1.4 on 2020-12-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_opponent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
