# Generated by Django 3.1.4 on 2020-12-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201219_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_creator',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_opponent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
